#!/usr/bin/env bash


# Check if a password was provided
if [ -z "$1" ]; then
	  echo "Error: No password provided."
	    exit 1
fi

# Get the current date in the format day-month-year
date=$(date +%d-%m-%Y)

# Generate the MySQL dump and save it to a file named backup.sql
mysqldump -u root -p$1 --all-databases > backup.sql

# Check if the MySQL dump was successful
if [ $? -ne 0 ]; then
	  echo "Error: MySQL dump failed."
	    exit 1
fi

# Compress the MySQL dump to a tar.gz archive with the name format day-month-year.tar.gz
tar -czvf $date.tar.gz backup.sql

# Remove the MySQL dump file
rm backup.sql

echo "MySQL dump and compress successful."
