#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds
# Script 101-manage_my_process file manages script manage_my_process file

startme()
{
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
}
stopme()
{
    sudo kill -15 "$(cat /var/run/my_process.pid)"
    rm -f /var/run/my_process.pid
}
case "$1" in
    start) startme
	   echo "manage_my_process started"
	   ;;
    stop) stopme
	  echo "manage_my_process stopped"
	  ;;
    restart) stopme
	     startme
             echo "manage_my_process restarted"
	     ;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
       ;;
esac
exit 0
